### ISSUE TITLE
Error in foodshops_sv.lua 29:33

### ISSUE THREAD

**Issue by 4xx22** [gabsgold/gb_needs#5]
Hello,

I have this when I want to buy something : 
![y9xdk59](https://cloud.githubusercontent.com/assets/17505454/26259817/093efb8a-3ccb-11e7-8e97-91b033cb4ad6.png)

(I use VDK) 

Have a good day

**Comment by gabsgold** [comment]
Hi,
Can you try without any other script? Just to be sure that this error is not generated because of another script.
I already saw this error a long time ago and it came from another script.

best regard.

**Comment by 4xx22** [comment]
Hi,

I have found the problem, I just accidentally change the bad value : 
![xhufpwu](https://cloud.githubusercontent.com/assets/17505454/26284549/5db4c306-3e3e-11e7-8242-4b39da742a59.png)

Sorry ;)
