### ISSUE TITLE
Que ce passe t il quand le compteur arrive a 0 ?

### ISSUE THREAD

**Issue by Applemaniac** [gabsgold/gb_needs#9]
Y aurait il moyen que vous fassiez subir des dégâts au player lors que sa barre de nourriture, de soif atteignent 0 ou sa barre de WC arrive a 100 ? Merci de votre réponse, super script <3

**Comment by 4xx22** [comment]
Salut, 

Actuellement la personne meurt si elle atteint 0 ^^

**Comment by Applemaniac** [comment]
et a 100 de WC ?

**Comment by Applemaniac** [comment]
https://i.imgur.com/zgbdmhu.jpg Je ne suis pas mort :/

**Comment by Applemaniac** [comment]
Okey j'ai compris il faut juste que j'attende
